version: "3.8"

services:
  slurm_db:
    image: mysql:latest
    hostname: slurm_db
    container_name: slurm_db
      
    # NOTE:
    # use of "mysql_native_password" is not recommended:
    #   https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    #
    # This configuration assumes local EDA/DEV/etc. use only; NEVER use this 
    # approach in production. You have been warned!
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=4096M --innodb-log-file-size=64M --innodb-lock-wait-timeout=900
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=H3ll012Three
    volumes:
      - type: bind
        source: ./slurm_db
        target: /var/lib/mysql/
      - ./sql-scripts:/docker-entrypoint-initdb.d
