version: "3.8"

x-defaults:
  &default-settings
  hostname: ${CONTAINER_HOSTNAME}
  tty: true

x-defaults-build-standard:
  &default-build-args-standard
  args:
    - BASE_DOCKER_REPO=${DOCKER_HUB_REPO}
    - BASE_TAG=${TAG_BASE_ROOT}
    - UBUNTU_VERSION=${CONTAINER_UBUNTU_VERSION}
    - USERNAME=${CONTAINER_USERNAME}
    - PASSWORD=${CONTAINER_PASSWORD}
    - UID=${CONTAINER_UID}
    - TIMEZONE=${CONTAINER_TIMEZONE}
    - USER_PRIVILEGE_LEVEL=standard

x-defaults-build-root:
  &default-build-args-root
  args:
    - BASE_DOCKER_REPO=${DOCKER_HUB_REPO}
    - BASE_TAG=${TAG_BASE_ROOT}
    - UBUNTU_VERSION=${CONTAINER_UBUNTU_VERSION}
    - USERNAME=${CONTAINER_USERNAME}
    - PASSWORD=${CONTAINER_PASSWORD}
    - UID=${CONTAINER_UID}
    - TIMEZONE=${CONTAINER_TIMEZONE}
    - USER_PRIVILEGE_LEVEL=root

services:
  psrc_db:
    image: mysql:latest
    hostname: slurm_db
    container_name: slurm_db
    ports:
      - 3306:3306
      
    # NOTE:
    # use of "mysql_native_password" is not recommended:
    #   https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    #
    # This configuration assumes local EDA use only, NEVER use this approach
    # in production.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=H3ll012Three
    volumes:
      - type: bind
        source: ./slurm_db
        target: /var/lib/mysql/
      - ./sql-scripts:/docker-entrypoint-initdb.d

  build-base-root:
    << : *default-settings
    build:
      context: ./dockerfile_base
      << : *default-build-args-root
    image: ${DOCKER_HUB_REPO}:${TAG_BASE_ROOT}
    container_name: slurm-${TAG_BASE_ROOT}
