services:
  slurm_db:
    image: mysql:9.0
    hostname: slurm_db
    container_name: slurm_db
      
    # NOTE:
    # This configuration assumes local EDA/DEV/etc. use only; NEVER use this 
    # approach in production. You have been warned!
    command: --innodb-buffer-pool-size=4096M --innodb-redo-log-capacity=256M --innodb-lock-wait-timeout=900
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=H3ll012Three
    volumes:
      - type: bind
        source: ./slurm_db
        target: /var/lib/mysql/
      - ./sql-scripts:/docker-entrypoint-initdb.d
