version: "3.8"

x-defaults:
  &default-settings
  hostname: ${CONTAINER_HOSTNAME}
  tty: true

x-defaults-build-standard:
  &default-build-args-standard
  args:
    - BASE_DOCKER_REPO=${DOCKER_HUB_REPO}
    - BASE_TAG=${TAG_BASE_ROOT}
    - USERNAME=${CONTAINER_USERNAME}
    - PASSWORD=${CONTAINER_PASSWORD}
    - UID=${CONTAINER_UID}
    - GID=${CONTAINER_GID}
    - TIMEZONE=${CONTAINER_TIMEZONE}
    - USER_PRIVILEGE_LEVEL=standard

x-defaults-build-root:
  &default-build-args-root
  << : *default-build-args-standard
  args:
    - USER_PRIVILEGE_LEVEL=root

services:
  base:
    << : *default-settings
    image: ${DOCKER_HUB_REPO}:${TAG_BASE_STANDARD}
    container_name: slurm-${TAG_BASE_STANDARD}
  base-root:
    << : *default-settings
    image: ${DOCKER_HUB_REPO}:${TAG_BASE_ROOT}
    container_name: slurm-${TAG_BASE_ROOT}

  full:
    << : *default-settings
    image: ${DOCKER_HUB_REPO}:${TAG_FULL_STANDARD}
    container_name: slurm-${TAG_FULL_STANDARD}
  full-root:
    << : *default-settings
    image: ${DOCKER_HUB_REPO}:${TAG_FULL_ROOT}
    container_name: slurm-${TAG_FULL_ROOT}

  build-base:
    << : *default-settings
    build:
      context: ./dockerfile_base
      << : *default-build-args-standard
    image: ${DOCKER_HUB_REPO}:${TAG_BASE_STANDARD}
    container_name: slurm-${TAG_BASE_STANDARD}
  build-base-root:
    << : *default-settings
    build:
      context: ./dockerfile_base
      << : *default-build-args-root
    image: ${DOCKER_HUB_REPO}:${TAG_BASE_ROOT}
    container_name: slurm-${TAG_BASE_ROOT}

  build-full:
    << : *default-settings
    build:
      context: ./dockerfile_full
      << : *default-build-args-standard
    image: ${DOCKER_HUB_REPO}:${TAG_FULL_STANDARD}
    container_name: slurm-${TAG_FULL_STANDARD}
  build-full-root:
    << : *default-settings
    build:
      context: ./dockerfile_full
      << : *default-build-args-root
    image: ${DOCKER_HUB_REPO}:${TAG_FULL_ROOT}
    container_name: slurm-${TAG_FULL_ROOT}
