name: Docker Image Testing

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  test:
    name: Docker Test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Files
        uses: actions/checkout@v3

      - name: Set Up Runner
        uses: './.github/workflows/composite-actions/setup'

      - name: Test Docker Image - base - standard
        if: ${{ always() }}
        uses: './.github/workflows/composite-actions/test'
        with:
          user: standard
          docker_build_context: dockerfile_base/

      - name: Test Docker Image - base - root
        if: ${{ always() }}
        uses: './.github/workflows/composite-actions/test'
        with:
          user: root
          docker_build_context: dockerfile_base/

      - name: Build Image - base/root (full image dependency)
        uses: './.github/workflows/composite-actions/docker-build-push'
        with:
          user: root
          context: dockerfile_base/
          load: 'true'
          push: 'false'
          tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.TAG_BASE_ROOT }}

      - name: Test Docker Image - full - standard
        if: ${{ always() }}
        uses: './.github/workflows/composite-actions/test'
        with:
          user: standard
          docker_build_context: dockerfile_full/
          required_images: ${{ env.DOCKER_HUB_REPO }}:${{ env.TAG_BASE_ROOT }}

      - name: Test Docker Image - full - root
        if: ${{ always() }}
        uses: './.github/workflows/composite-actions/test'
        with:
          user: root
          docker_build_context: dockerfile_full/
          required_images: ${{ env.DOCKER_HUB_REPO }}:${{ env.TAG_BASE_ROOT }}
